<meta charset="UTF-8">

title: 半盏白茶的主页
page-top-title: BanzhanBaicha
top-section-bg-text: 万里浮云卷碧山<br>Endless Clouds Rolling Over Jade Mountains
home-subtitle: Yourname&ensp;|&ensp;BanzhanBaicha
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
